spring:
  application:
    name: wallet
  datasource:
    url: jdbc:postgresql://localhost:5432/hogwarts
    username: student
    password: chocolatefrog
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:liquibase/changelog-master.yml

path:
  to:
    avatars:
      folder: avatars

logging:
  level:
    root: info

server:
  port: 8080